# Input/output file
import numpy as np

class IO:

    def load_expt(filename):
        """
        Load experimental cell tracking data from a text file. Return
        time (s), positions (mu_m) and smoothed positions (mu_m).
        """

        t, x, y, z, xs, ys, zs = np.loadtxt(filename,unpack=True,
                usecols=[0,1,2,3,4,5,6])

        # output track data in same array format as model
        pos = []
        pos_s = []
        for i in range(0,len(x)):
            pos.append(np.array([x[i],y[i],z[i]]))
            pos_s.append(np.array([xs[i],ys[i],zs[i]]))

        pos = np.array(pos)
        pos_s = np.array(pos_s)

        return t, pos, pos_s

    def save_model(filename, data_list, format_list, title=""):
        """
        Save model data generated by the simulation as columns to a
        text file. Maintains the same format as the experimental
        data files. Data delimited by four spaces (tab).

        data_list is a python list containing numpy arrays of data,
        i.e. data_list=[x,y,z] where x=np.array([1,2,3,4]), etc.

        format_list contains the string formats corresponding to the
        data in data_list.
        e.g. %6.3f will write a float as 12.345, %3.1 as 1.2, etc.
        """

        np.savetxt(fname=filename, X=np.transpose(data_list),
            fmt=format_list, delimiter="\t",header=title)

