"""
RandomWalks - A code to simulate run-and-tumble swimming and Brownian motion
    
Copyright (C) 2019  R.C.T.B. Cocking

Email: rctc500@york.ac.uk

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# Input/output file
import numpy as np

class IO:

    def load_expt(filename):
        """
        Load experimental cell tracking data from a text file. Return
        time (sec), positions (mu) and smoothed positions (mu).
        """

        t, x, y, z, xs, ys, zs = np.loadtxt(filename,unpack=True,
                usecols=[0,1,2,3,4,5,6])

        # output track data in same array format as model
        pos = []
        pos_s = []
        for i in range(0,len(x)):
            pos.append(np.array([x[i],y[i],z[i]]))
            pos_s.append(np.array([xs[i],ys[i],zs[i]]))

        pos = np.array(pos)
        pos_s = np.array(pos_s)

        return t, pos, pos_s

    def save_model(filename, data_list, format_list, title=""):
        """
        Save model data generated by the simulation as columns to a
        text file. Maintains the same format as the experimental
        data files. Data delimited by four spaces (tab).

        data_list is a python list containing numpy arrays of data,
        i.e. data_list=[x,y,z] where x=np.array([1,2,3,4]), etc.

        format_list contains the string formats corresponding to the
        data in data_list.
        e.g. %6.3f will write a float as 12.345, %3.1 as 1.2, etc.
        """

        np.savetxt(fname=filename, X=np.transpose(data_list),
            fmt=format_list, delimiter="\t",header=title)

